### ISSUE TITLE
Hosting for database

### ISSUE THREAD

**Issue by andrewseling** [ColumbusCollabDevOps/Express-example#1]
Nate will look into hosting database on AWS - possibly Dynamo.

**Comment by nhinshaw** [comment]
found some interesting info about geo data in dynamo. Posting here for reference. 

https://github.com/awslabs/dynamodb-geo

Basically we need a java instance in front of the data to handle the type of queries. I found some other not so nice ways to make this happen as well. It may be easier to just run the container in ECS on a micro spot instance to keep it cheap.

Athena has some capabilities around geo data as well but i haven't been able to wrap my head around it yet.
